// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/reservas/1/1": {
    params: {};
  };
  "/reservas/1/2": {
    params: {};
  };
  "/reservas/1/3": {
    params: {};
  };
  "/reservas/2/1": {
    params: {};
  };
  "/reservas/2/2": {
    params: {};
  };
  "/reservas/2/3": {
    params: {};
  };
  "/reservas/3/1": {
    params: {};
  };
  "/reservas/3/2": {
    params: {};
  };
  "/reservas/3/3": {
    params: {};
  };
  "/reservas/4/1": {
    params: {};
  };
  "/reservas/4/2": {
    params: {};
  };
  "/reservas/4/3": {
    params: {};
  };
  "/reservas/5/1": {
    params: {};
  };
  "/reservas/5/2": {
    params: {};
  };
  "/reservas/5/3": {
    params: {};
  };
  "/reservas/6/1": {
    params: {};
  };
  "/reservas/6/2": {
    params: {};
  };
  "/reservas/6/3": {
    params: {};
  };
  "/reservas/7/1": {
    params: {};
  };
  "/reservas/7/2": {
    params: {};
  };
  "/reservas/7/3": {
    params: {};
  };
  "/reservas/8/1": {
    params: {};
  };
  "/reservas/8/2": {
    params: {};
  };
  "/reservas/8/3": {
    params: {};
  };
  "/pelicula/1": {
    params: {};
  };
  "/pelicula/2": {
    params: {};
  };
  "/pelicula/3": {
    params: {};
  };
  "/pelicula/4": {
    params: {};
  };
  "/pelicula/5": {
    params: {};
  };
  "/pelicula/6": {
    params: {};
  };
  "/pelicula/7": {
    params: {};
  };
  "/pelicula/8": {
    params: {};
  };
  "/proximamente": {
    params: {};
  };
  "/cartelera": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/reservas/1/1" | "/reservas/1/2" | "/reservas/1/3" | "/reservas/2/1" | "/reservas/2/2" | "/reservas/2/3" | "/reservas/3/1" | "/reservas/3/2" | "/reservas/3/3" | "/reservas/4/1" | "/reservas/4/2" | "/reservas/4/3" | "/reservas/5/1" | "/reservas/5/2" | "/reservas/5/3" | "/reservas/6/1" | "/reservas/6/2" | "/reservas/6/3" | "/reservas/7/1" | "/reservas/7/2" | "/reservas/7/3" | "/reservas/8/1" | "/reservas/8/2" | "/reservas/8/3" | "/pelicula/1" | "/pelicula/2" | "/pelicula/3" | "/pelicula/4" | "/pelicula/5" | "/pelicula/6" | "/pelicula/7" | "/pelicula/8" | "/proximamente" | "/cartelera" | "/*";
  };
  "routes/[reservas].[1].[1]._index.jsx": {
    id: "routes/[reservas].[1].[1]._index";
    page: "/reservas/1/1";
  };
  "routes/[reservas].[1].[2]._index.jsx": {
    id: "routes/[reservas].[1].[2]._index";
    page: "/reservas/1/2";
  };
  "routes/[reservas].[1].[3]._index.jsx": {
    id: "routes/[reservas].[1].[3]._index";
    page: "/reservas/1/3";
  };
  "routes/[reservas].[2].[1]._index.jsx": {
    id: "routes/[reservas].[2].[1]._index";
    page: "/reservas/2/1";
  };
  "routes/[reservas].[2].[2]._index.jsx": {
    id: "routes/[reservas].[2].[2]._index";
    page: "/reservas/2/2";
  };
  "routes/[reservas].[2].[3]._index.jsx": {
    id: "routes/[reservas].[2].[3]._index";
    page: "/reservas/2/3";
  };
  "routes/[reservas].[3].[1]._index.jsx": {
    id: "routes/[reservas].[3].[1]._index";
    page: "/reservas/3/1";
  };
  "routes/[reservas].[3].[2]._index.jsx": {
    id: "routes/[reservas].[3].[2]._index";
    page: "/reservas/3/2";
  };
  "routes/[reservas].[3].[3]._index.jsx": {
    id: "routes/[reservas].[3].[3]._index";
    page: "/reservas/3/3";
  };
  "routes/[reservas].[4].[1]._index.jsx": {
    id: "routes/[reservas].[4].[1]._index";
    page: "/reservas/4/1";
  };
  "routes/[reservas].[4].[2]._index.jsx": {
    id: "routes/[reservas].[4].[2]._index";
    page: "/reservas/4/2";
  };
  "routes/[reservas].[4].[3]._index.jsx": {
    id: "routes/[reservas].[4].[3]._index";
    page: "/reservas/4/3";
  };
  "routes/[reservas].[5].[1]._index.jsx": {
    id: "routes/[reservas].[5].[1]._index";
    page: "/reservas/5/1";
  };
  "routes/[reservas].[5].[2]._index.jsx": {
    id: "routes/[reservas].[5].[2]._index";
    page: "/reservas/5/2";
  };
  "routes/[reservas].[5].[3]._index.jsx": {
    id: "routes/[reservas].[5].[3]._index";
    page: "/reservas/5/3";
  };
  "routes/[reservas].[6].[1]._index.jsx": {
    id: "routes/[reservas].[6].[1]._index";
    page: "/reservas/6/1";
  };
  "routes/[reservas].[6].[2]._index.jsx": {
    id: "routes/[reservas].[6].[2]._index";
    page: "/reservas/6/2";
  };
  "routes/[reservas].[6].[3]._index.jsx": {
    id: "routes/[reservas].[6].[3]._index";
    page: "/reservas/6/3";
  };
  "routes/[reservas].[7].[1]._index.jsx": {
    id: "routes/[reservas].[7].[1]._index";
    page: "/reservas/7/1";
  };
  "routes/[reservas].[7].[2]._index.jsx": {
    id: "routes/[reservas].[7].[2]._index";
    page: "/reservas/7/2";
  };
  "routes/[reservas].[7].[3]._index.jsx": {
    id: "routes/[reservas].[7].[3]._index";
    page: "/reservas/7/3";
  };
  "routes/[reservas].[8].[1]._index.jsx": {
    id: "routes/[reservas].[8].[1]._index";
    page: "/reservas/8/1";
  };
  "routes/[reservas].[8].[2]._index.jsx": {
    id: "routes/[reservas].[8].[2]._index";
    page: "/reservas/8/2";
  };
  "routes/[reservas].[8].[3]._index.jsx": {
    id: "routes/[reservas].[8].[3]._index";
    page: "/reservas/8/3";
  };
  "routes/[pelicula].[1]._index.jsx": {
    id: "routes/[pelicula].[1]._index";
    page: "/pelicula/1";
  };
  "routes/[pelicula].[2]._index.jsx": {
    id: "routes/[pelicula].[2]._index";
    page: "/pelicula/2";
  };
  "routes/[pelicula].[3]._index.jsx": {
    id: "routes/[pelicula].[3]._index";
    page: "/pelicula/3";
  };
  "routes/[pelicula].[4]._index.jsx": {
    id: "routes/[pelicula].[4]._index";
    page: "/pelicula/4";
  };
  "routes/[pelicula].[5]._index.jsx": {
    id: "routes/[pelicula].[5]._index";
    page: "/pelicula/5";
  };
  "routes/[pelicula].[6]._index.jsx": {
    id: "routes/[pelicula].[6]._index";
    page: "/pelicula/6";
  };
  "routes/[pelicula].[7]._index.jsx": {
    id: "routes/[pelicula].[7]._index";
    page: "/pelicula/7";
  };
  "routes/[pelicula].[8]._index.jsx": {
    id: "routes/[pelicula].[8]._index";
    page: "/pelicula/8";
  };
  "routes/[proximamente]._index.jsx": {
    id: "routes/[proximamente]._index";
    page: "/proximamente";
  };
  "routes/[cartelera]._index.jsx": {
    id: "routes/[cartelera]._index";
    page: "/cartelera";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[reservas].[1].[1]._index": typeof import("./app/routes/[reservas].[1].[1]._index.jsx");
  "routes/[reservas].[1].[2]._index": typeof import("./app/routes/[reservas].[1].[2]._index.jsx");
  "routes/[reservas].[1].[3]._index": typeof import("./app/routes/[reservas].[1].[3]._index.jsx");
  "routes/[reservas].[2].[1]._index": typeof import("./app/routes/[reservas].[2].[1]._index.jsx");
  "routes/[reservas].[2].[2]._index": typeof import("./app/routes/[reservas].[2].[2]._index.jsx");
  "routes/[reservas].[2].[3]._index": typeof import("./app/routes/[reservas].[2].[3]._index.jsx");
  "routes/[reservas].[3].[1]._index": typeof import("./app/routes/[reservas].[3].[1]._index.jsx");
  "routes/[reservas].[3].[2]._index": typeof import("./app/routes/[reservas].[3].[2]._index.jsx");
  "routes/[reservas].[3].[3]._index": typeof import("./app/routes/[reservas].[3].[3]._index.jsx");
  "routes/[reservas].[4].[1]._index": typeof import("./app/routes/[reservas].[4].[1]._index.jsx");
  "routes/[reservas].[4].[2]._index": typeof import("./app/routes/[reservas].[4].[2]._index.jsx");
  "routes/[reservas].[4].[3]._index": typeof import("./app/routes/[reservas].[4].[3]._index.jsx");
  "routes/[reservas].[5].[1]._index": typeof import("./app/routes/[reservas].[5].[1]._index.jsx");
  "routes/[reservas].[5].[2]._index": typeof import("./app/routes/[reservas].[5].[2]._index.jsx");
  "routes/[reservas].[5].[3]._index": typeof import("./app/routes/[reservas].[5].[3]._index.jsx");
  "routes/[reservas].[6].[1]._index": typeof import("./app/routes/[reservas].[6].[1]._index.jsx");
  "routes/[reservas].[6].[2]._index": typeof import("./app/routes/[reservas].[6].[2]._index.jsx");
  "routes/[reservas].[6].[3]._index": typeof import("./app/routes/[reservas].[6].[3]._index.jsx");
  "routes/[reservas].[7].[1]._index": typeof import("./app/routes/[reservas].[7].[1]._index.jsx");
  "routes/[reservas].[7].[2]._index": typeof import("./app/routes/[reservas].[7].[2]._index.jsx");
  "routes/[reservas].[7].[3]._index": typeof import("./app/routes/[reservas].[7].[3]._index.jsx");
  "routes/[reservas].[8].[1]._index": typeof import("./app/routes/[reservas].[8].[1]._index.jsx");
  "routes/[reservas].[8].[2]._index": typeof import("./app/routes/[reservas].[8].[2]._index.jsx");
  "routes/[reservas].[8].[3]._index": typeof import("./app/routes/[reservas].[8].[3]._index.jsx");
  "routes/[pelicula].[1]._index": typeof import("./app/routes/[pelicula].[1]._index.jsx");
  "routes/[pelicula].[2]._index": typeof import("./app/routes/[pelicula].[2]._index.jsx");
  "routes/[pelicula].[3]._index": typeof import("./app/routes/[pelicula].[3]._index.jsx");
  "routes/[pelicula].[4]._index": typeof import("./app/routes/[pelicula].[4]._index.jsx");
  "routes/[pelicula].[5]._index": typeof import("./app/routes/[pelicula].[5]._index.jsx");
  "routes/[pelicula].[6]._index": typeof import("./app/routes/[pelicula].[6]._index.jsx");
  "routes/[pelicula].[7]._index": typeof import("./app/routes/[pelicula].[7]._index.jsx");
  "routes/[pelicula].[8]._index": typeof import("./app/routes/[pelicula].[8]._index.jsx");
  "routes/[proximamente]._index": typeof import("./app/routes/[proximamente]._index.jsx");
  "routes/[cartelera]._index": typeof import("./app/routes/[cartelera]._index.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};